apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-storage-api
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-storage-api
  template:
    metadata:
      labels:
        app: nano35-storage-api
    spec:
      containers:
        - name: nano35-storage-api
          image: bushemi2021/nano35.storage.api:latest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-storage-projection
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-storage-projection
  template:
    metadata:
      labels:
        app: nano35-storage-projection
    spec:
      containers:
        - name: nano35-storage-projection
          image: bushemi2021/nano35.storage.projection:latest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nano35-storage-processor
  namespace: nano35
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano35-storage-processor
  template:
    metadata:
      labels:
        app: nano35-storage-processor
    spec:
      containers:
        - name: nano35-storage-processor
          image: bushemi2021/nano35.storage.processor:latest
          
---

apiVersion: v1
kind: Service
metadata:
  name: nano35-storage-entrypoint
  namespace: nano35
spec:
  type: NodePort
  selector:
    app: nano35-storage-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30101

---

apiVersion: v1
kind: Service
metadata:
  name: nano35-storage-entrypoint
  namespace: nano35
spec:
  type: NodePort
  selector:
    app: nano35-storage-projection
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30201