apiVersion: v1
kind: Service
metadata:
  namespace: nano35
  name: nano35-storage-projection-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30050
  selector:
    app: nano35-storage-projection
